name: Flatpak Build

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    name: Flatpak Build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
     
    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake build-essential cmake git libnuma-dev libtool libtool-bin m4 make meson nasm ninja-build patch pkg-config tar flatpak flatpak-builder
        sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.gnome.Platform//49 org.gnome.Sdk//49 org.freedesktop.Sdk.Extension.llvm21//25.08 org.freedesktop.Sdk.Extension.rust-stable//25.08
   
    - name: Build HandBrake
      run: |
        ./configure --launch-jobs=1 --flatpak --enable-qsv --enable-vce --enable-nvdec --enable-libdovi
        cd build
        nice make pkg.create.gui.flatpak

    - name: Build HandBrake Plugins
      run: |
        cd build
        nice make pkg.create.plugins.flatpak
        
    - name: Upload Package
      uses: actions/upload-artifact@v6
      with:
        name: HandBrake
        path: ./build/pkg/flatpak/*.flatpak
