name: macOS build

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build on macOS
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13.7'

    - name: Toolchain Cache
      id: mac-toolchain
      uses: actions/cache@v4
      with:
        path: ~/mac-toolchain
        key: ${{ runner.os }}-${{ runner.arch }}-toolchain-${{ hashFiles('**/scripts/mac-toolchain-build') }}

    - name: Cargo-C Toolchain Cache
      id: mac-cargo-c-toolchain
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/cargo-capi
          ~/.cargo/bin/cargo-cbuild
          ~/.cargo/bin/cargo-cinstall
        key: ${{ runner.os }}-${{ runner.arch }}-cargo-c-toolchain-${{ hashFiles('**/scripts/mac-toolchain-build') }}

    - name: Setup Environment
      run: |
        echo ~/mac-toolchain/bin >> $GITHUB_PATH
        rustup target add x86_64-apple-darwin
        xcodebuild -downloadComponent MetalToolchain

    - name: Setup Toolchain
      if: steps.mac-toolchain.outputs.cache-hit != 'true'
      run: |
        pip install setuptools
        scripts/mac-toolchain-build ~/mac-toolchain

    - name: Setup Cargo-C Toolchain
      if: steps.mac-cargo-c-toolchain.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-c

    - name: Build HandBrake
      run: |
        ./configure
        cd build
        make ub && make pkg.create

    - name: Upload Assets
      uses: actions/upload-artifact@v5
      with:
        name: HandBrake-macos
        path: ./build/pkg
