name: macOS build

on: [push, pull_request]

jobs:
  build:
    name: Build on macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Toolchain Cache
      id: mac-toolchain
      uses: actions/cache@v3
      with:
        path: ~/mac-toolchain
        key: mac-toolchain

    - name: Setup Path
      run: |
        echo ~/mac-toolchain/bin >> $GITHUB_PATH

    - name: Setup Environment
      if: steps.mac-toolchain.outputs.cache-hit != 'true'
      run: |
        scripts/mac-toolchain-build ~/mac-toolchain

    - name: Build HandBrake
      run: |
        git submodule update --init --recursive
        ./configure
        cd build
        make ub && make pkg.create

    - name: Upload Assets
      uses: actions/upload-artifact@v2
      with:
        name: HandBrake-macos
        path: ./build/pkg
